homeassistant:
  name: Home
  elevation: 0
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml
  
http:
  ip_ban_enabled: true
  login_attempts_threshold: 5
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  base_url: !secret base_url

frontend:
  themes: !include_dir_merge_named themes
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-custom-ui-es5.html
  
config:

mobile_app:

fastdotcom:

discovery:
  ignore:
    - philips_hue

updater:

history:

ios:
  push:
    categories:
      - name: Alarm
        identifier: 'alarm'
        actions:
          - identifier: 'RESTART_WLED'
            title: 'Restart WLED'
            authenticationMode: 'background'
            authenticationRequired: no
            destructive: true
            behavior: 'default'
          - identifier: 'DISMISS'
            title: 'Dismiss'
            authenticationMode: 'background'
            authenticationRequired: no
            destructive: false
            behavior: 'default'
      - name: Door
        identifier: 'door'
        actions:
          - identifier: 'LOCK_DOOR'
            title: 'Lock Door'
            authenticationMode: 'background'
            authenticationRequired: no
            destructive: true
            behavior: 'default'
          - identifier: 'DISMISS'
            title: 'Dismiss'
            authenticationMode: 'background'
            authenticationRequired: no
            destructive: false
            behavior: 'default'

emulated_hue:
  listen_port: 80

logger:

stream:

homekit:
  filter:
    exclude_domains: [calendar]

panel_iframe:
  ide:
    title: "IDE"
    icon: mdi:code-braces
    url: !secret ide_link
    
system_health:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
group: !include groups.yaml
light: !include lights.yaml
media_player: !include media-player.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include sensor.yaml
shell_command: !include shell.yaml
switch: !include switch.yaml