homeassistant: !include home.yaml
http: !include http.yaml
frontend: !include frontend.yaml

config:

discovery: !include discovery.yaml

updater:
history:
logger:
mobile_app:
stream:
system_health:
zha_map:

emulated_hue: !include emulated-hue.yaml
fastdotcom: !include fast.yaml
ios: !include ios.yaml
panel_iframe: !include panel.yaml
octoprint: !include octoprint.yaml
tplink: !include tplink.yaml
tts: !include tts.yaml
zha: !include zha.yaml

automation: !include automations.yaml
binary_sensor: !include binary-sensor.yaml
camera: !include camera.yaml
group: !include groups.yaml
light: !include lights.yaml
media_player: !include media-player.yaml
remote: !include remote.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include sensor.yaml
shell_command: !include shell.yaml
switch: !include switch.yaml
