homeassistant: !include configurations/home.yaml
http: !include configurations/http.yaml
frontend: !include configurations/frontend.yaml

config:

discovery: !include configurations/discovery.yaml

updater:
history:
logger:
mobile_app:
stream:
system_health:

emulated_hue: !include configurations/emulated-hue.yaml
fastdotcom: !include configurations/fast.yaml
ios: !include configurations/ios.yaml
panel_iframe: !include configurations/panel.yaml
octoprint: !include configurations/octoprint.yaml
speedtestdotnet: !include configurations/speedtest.yaml
tplink: !include configurations/tplink.yaml
tts: !include configurations/tts.yaml
zha: !include configurations/zha.yaml

automation: !include configurations/automations.yaml
binary_sensor: !include configurations/binary-sensor.yaml
camera: !include configurations/camera.yaml
group: !include configurations/groups.yaml
light: !include configurations/lights.yaml
media_player: !include configurations/media-player.yaml
remote: !include configurations/remote.yaml
scene: !include configurations/scenes.yaml
script: !include configurations/scripts.yaml
sensor: !include configurations/sensor.yaml
shell_command: !include configurations/shell.yaml
switch: !include configurations/switch.yaml
