- platform: seventeentrack
  username: !secret 17_user
  password: !secret 17_pass
  
- platform: template
  sensors:
    tv_estimated_current_3_a:
      friendly_name: "TV"
      unit_of_measurement: "A"
      value_template: '{{ states.sensor.wled_estimated_current_3.state | multiply(0.001) | round(3) }}'
    wled_maker_select_estimated_current_a:
      friendly_name: "Maker Select"
      unit_of_measurement: "A"
      value_template: '{{ states.sensor.wled_maker_select_estimated_current.state | multiply(0.001) | round(3) }}'
    wled_nano_leaves_estimated_current_a:
      friendly_name: "Nano Leaf"
      unit_of_measurement: "A"
      value_template: '{{ states.sensor.wled_nano_leaves_estimated_current.state | multiply(0.001) | round(3) }}'
   
- platform: mitemp_bt
  mac: 'A4:C1:38:E9:E6:10'
  monitored_conditions:
    - temperature
    - humidity
    - battery

- platform: cpuspeed
  name: processor_use

- platform: command_line
  name: cpu_temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'
    
- platform: systemmonitor
  resources:
      - type: disk_use_percent
        arg: /
      - type: disk_use
        arg: /
      - type: disk_free
        arg: /
      - type: memory_use_percent
      - type: memory_use
      - type: memory_free
      - type: ipv4_address
        arg: eth0
      - type: last_boot
      - type: network_in
        arg: eth0
      - type: network_out
        arg: eth0