custom_header:
  button_text:
    options: "{{ hours12 }}:{{ minutesLZ }} {{ ampm }}"
  compact_mode: true
  hide_help: true
  hide_unused: true
title: ""
views:
  - badges: []
    cards:
      - cards:
          - cards:
              - decimals: 3
                align_state: center
                entities:
                  - color: red
                    entity: sensor.ambilight_estimated_current_a
                    name: Ambilight
                font_size: 100
                height: 300
                icon: "mdi:flash"
                name: Ambilight
                points_per_hour: 5
                show:
                  average: false
                  fill: false
                  graph: false
                  icon: false
                  labels: false
                  labels_secondary: false
                  legend: false
                  name: true
                  state: false
                align_header: center
                type: "custom:mini-graph-card"
                update_interval: 300
              - decimals: 3
                align_state: center
                entities:
                  - color: white
                    entity: sensor.wled_desk_estimated_current_a
                    name: Desk
                font_size: 100
                height: 300
                icon: "mdi:flash"
                name: Desk
                points_per_hour: 5
                show:
                  average: false
                  fill: false
                  graph: false
                  icon: false
                  labels: false
                  labels_secondary: false
                  legend: false
                  name: true
                  state: false
                align_header: center
                type: "custom:mini-graph-card"
                update_interval: 300
              - decimals: 3
                align_state: center
                entities:
                  - color: green
                    entity: sensor.wled_bench_estimated_current_a
                    name: Bench
                font_size: 100
                height: 300
                icon: "mdi:flash"
                name: Bench
                points_per_hour: 5
                show:
                  average: false
                  fill: false
                  graph: false
                  icon: false
                  labels: false
                  labels_secondary: false
                  legend: false
                  name: true
                  state: false
                align_header: center
                type: "custom:mini-graph-card"
                update_interval: 300
            type: horizontal-stack
          - cards:
              - entity: light.wled_tv_ambilight
                name: " "
                type: light
              - entity: light.wled_desk_master
                name: " "
                type: light
              - entity: light.wled_bench
                name: " "
                type: light
            type: horizontal-stack
          - cards:
              - decimals: 3
                align_state: center
                entities:
                  - color: red
                    entity: sensor.ambilight_estimated_current_a
                    name: Ambilight
                font_size: 80
                height: 300
                icon: "mdi:flash"
                name: Ambilight
                points_per_hour: 5
                show:
                  average: false
                  fill: false
                  graph: false
                  icon: false
                  labels: false
                  labels_secondary: false
                  legend: false
                  name: false
                  state: true
                align_header: center
                type: "custom:mini-graph-card"
                update_interval: 300
              - decimals: 3
                align_state: center
                entities:
                  - color: white
                    entity: sensor.wled_desk_estimated_current_a
                    name: Desk
                font_size: 80
                height: 300
                icon: "mdi:flash"
                name: Desk
                points_per_hour: 5
                show:
                  average: false
                  fill: false
                  graph: false
                  icon: false
                  labels: false
                  labels_secondary: false
                  legend: false
                  name: false
                  state: true
                align_header: center
                type: "custom:mini-graph-card"
                update_interval: 300
              - decimals: 3
                align_state: center
                entities:
                  - color: green
                    entity: sensor.wled_bench_estimated_current_a
                    name: Bench
                font_size: 80
                height: 300
                icon: "mdi:flash"
                name: Bench
                points_per_hour: 5
                show:
                  average: false
                  fill: false
                  graph: false
                  icon: false
                  labels: false
                  labels_secondary: false
                  legend: false
                  name: false
                  state: true
                align_header: center
                type: "custom:mini-graph-card"
                update_interval: 300
            type: horizontal-stack
          - decimals: 3
            align_state: center
            entities:
              - color: red
                entity: sensor.ambilight_estimated_current_a
                name: Ambilight
              - color: white
                entity: sensor.wled_desk_estimated_current_a
                name: Desk
              - color: green
                entity: sensor.wled_bench_estimated_current_a
                name: Bench
            font_size: 100
            height: 150
            icon: "mdi:flash"
            name: WLED Estimated Usage (Amps)
            points_per_hour: 5
            show:
              average: false
              icon: false
              labels: true
              labels_secondary: true
              name: false
              state: false
            align_header: center
            type: "custom:mini-graph-card"
            update_interval: 300
        type: vertical-stack
      - cards:
          - cards:
              - entity: lock.august_smart_lock_pro
                type: entity
              - entity: automation.restart_hyperion
                type: button
            type: horizontal-stack
          - artwork: cover
            entity: media_player.fire_stick_kodi
            name: Kodi | Fire Stick
            type: "custom:mini-media-player"
          - entities:
              - entity: group.living_room_lights
                name: Living Room
              - entity: group.window_lights
                name: Windows
              - entity: group.everything_else_lights
                name: Everything Else
              - entity: group.bedroom_lights
                name: Bedroom
            show_header_toggle: false
            type: entities
        type: vertical-stack
    icon: "mdi:home-circle"
    id: home
    panel: false
    path: default_view
    theme: ios-dark-mode
    title: Apartment
  - badges: []
    cards:
      - cards:
          - cards:
              - entity: switch.gosund_top_left
                name: Gosund Left
                type: button
              - entity: switch.gosund_top_right
                name: Gosund Right
                type: button
            type: horizontal-stack
          - align_state: center
            color_thresholds:
              - color: "#03C9EC"
                value: 80
              - color: "#0374EC"
                value: 90
              - color: "#0307EC"
                value: 95
            entities:
              - entity: sensor.monoprice_pir_sensor_1_relative_humidity_measurement
                name: Humidity
            height: 150
            icon: "mdi:water-percent"
            line_width: 2
            lower_bound: 85
            name: Humidity
            points_per_hour: 12
            show:
              average: false
              fill: fade
              icon_adaptive_color: true
              labels: true
              labels_secondary: true
              state: true
            smoothing: true
            type: "custom:mini-graph-card"
            unit: "%"
            update_interval: 300
          - align_state: center
            color_thresholds:
              - color: "#056BD8"
                value: 65
              - color: "#8C010B"
                value: 75
              - color: "#FF0719"
                value: 81
            entities:
              - entity: sensor.monoprice_pir_sensor_1_temperature_measurement
            height: 150
            icon: "mdi:thermometer-lines"
            line_width: 2
            name: Temperature
            points_per_hour: 12
            show:
              average: false
              fill: fade
              icon_adaptive_color: true
              labels: true
              labels_secondary: true
              state: true
            smoothing: true
            type: "custom:mini-graph-card"
            unit: °F
            update_interval: 300
        type: vertical-stack
    icon: "mdi:flower-poppy"
    path: ""
    title: a/v
